<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:scripting="http://www.mulesoft.org/schema/mule/scripting" xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/scripting http://www.mulesoft.org/schema/mule/scripting/current/mule-scripting.xsd">

	<import doc:name="Import" doc:id="9d8e1106-c9cf-4ff4-90ae-731f0b2ea807"
		file="test-tracer.xml" />

	<flow name="NestedExceptionWithCatchFlow" doc:id="a3759dc3-331e-40b9-ada7-33ef9d27a375" >
		<logger level="INFO" doc:name="Logger1" doc:id="a24a74d3-536e-41d5-98ae-a2774119fa3f" message="1"/>
		<flow-ref doc:name="Flow Reference" doc:id="eb85eef8-64d6-45f1-9964-23b750f420ea" name="NestedExceptionWithCatchFlow1"/>
		<logger level="INFO" doc:name="Logger2" doc:id="890aa645-e97e-40ce-b1e5-45b994283957" message="2"/>
		<error-handler >
			<on-error-continue enableNotifications="true" logException="true" doc:name="On Error Continue" doc:id="d69d1e86-c1e0-40ad-9a0a-aacf93246b17" type="ANY">
				<logger level="ERROR" doc:name="Logger4" doc:id="7d4f7f83-19d9-442f-83b8-367147dce19f" message="4"/>
			</on-error-continue>
		</error-handler>
	</flow>
	<flow name="NestedExceptionWithCatchFlow1" doc:id="7d19d956-e524-455e-9bf9-3defef536842" >
		<logger level="INFO" doc:name="Logger3" doc:id="0c67504e-d1a1-41e1-98cc-27cd85ba985c" message="3"/>
		<scripting:execute engine="groovy" doc:name="Execute" doc:id="524aff7e-6480-4377-a9b9-e4a9b7b9820c" >
			<scripting:code >throw new RuntimeException(&quot;this is a nested exception&quot;);</scripting:code>
		</scripting:execute>
	</flow>
</mule>
